"""empty message

Revision ID: 15620cff5fd1
Revises: 90ea14e00602
Create Date: 2022-08-15 16:17:07.953745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15620cff5fd1'
down_revision = '90ea14e00602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
