"""empty message

Revision ID: 5ba4148d50cd
Revises: 15620cff5fd1
Create Date: 2022-08-15 16:38:13.217784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba4148d50cd'
down_revision = '15620cff5fd1'
branch_labels = None
depends_on = None


def upgrade():
   
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.String(length=20),nullable=False,default='/static/profile_pics/default.jpg'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_column('image_file')
    # ### end Alembic commands ###


